### ISSUE TITLE
Cannot register account through Bitwarden-web

### ISSUE THREAD

**Issue by shackra** [VictorNine/bitwarden-go#12]
I have a [docker container for Bitwarden-go](https://gitlab.com/esavara/bitwarden-easy/blob/master/go/Dockerfile), the binary running inside is based on my pull request VictorNine/bitwarden-go/pull/8 that is [started this way](https://gitlab.com/esavara/dockersystemd/blob/master/docker-bitwarden-go.service).

I also have a [docker container for Bitwarden Vault](https://gitlab.com/esavara/bitwarden-easy/blob/master/web/Dockerfile) which [is told to point to http://localhost:8000](https://gitlab.com/esavara/bitwarden-easy/blob/master/web/settings.json) as there is were Bitwarden-go listens requests.

Bitwarden-go can response to requests perfectly fine:

```
jorge@morpho ~ % wget 0.0.0.0:8000/api/accounts/register          
--2018-01-05 04:13:34--  http://0.0.0.0:8000/api/accounts/register
Connecting to 0.0.0.0:8000... connected.
HTTP request sent, awaiting response... 400 Bad Request
2018-01-05 04:13:34 ERROR 400: Bad Request.
```

However, Bitwarden Vault tells me that "Errors have occurred. · An unexpected error has occurred." and I cannot register my account (or login, I put the credentials I cannot register and try to login but bitwarden vault displays the exact error message).

I don't have any output from the bitwarden-go binary indicating an error.

What am I doing wrong?

**Comment by ElCyborg** [comment]
Looking through your repo, it appears that your mirror is out of date, perhaps updating it could fix the problem? The last commit of your mirror seems to be 02995b9535030208dd843f8901b5c96e9eece6c7, decently old at this time.

**Comment by shackra** [comment]
On the mean time I will too update my repo with your recent changes and re-apply my additions and see what happens

**Comment by VictorNine** [comment]
The code is now part of this repo if you would like to try again

**Comment by shackra** [comment]
Nope, the weird error is still there even with the latest code for bitwarden-go compiled:

![screenshot-2018-1-30 register - bitwarden web vault](https://user-images.githubusercontent.com/1055216/35606297-e90462d4-0613-11e8-8ffa-59bc94b6c6c8.png)

**Comment by shackra** [comment]
Running everything locally (without docker) the behavior remains the same.

Bitwarden Vault is configure in this fashion:

```
{
  "appSettings": {
      "apiUri": "http://localhost:8000",
      "identityUri": "http://localhost:8000",
      "iconsUri": "https://icons.bitwarden.com",
      "stripeKey": "pk_test_KPoCfZXu7mznb9uSCPZ2JpTD",
      "braintreeKey": "sandbox_r72q8jq6_9pnxkwm75f87sdc2"
  }
}
```
and package.json is changed in its `env` variable:

```
...
   "env": "Development",
...
```

Not sure what is going on.

**Comment by VictorNine** [comment]
Looks like thats the problem. My setting.json file looks like this:

{
  "appSettings": {
    "apiUri": "/api",
    "identityUri": "/identity",
    "iconsUri": "https://icons.bitwarden.com",
    "stripeKey": "pk_test_KPoCfZXu7mznb9uSCPZ2JpTD",
    "braintreeKey": "sandbox_r72q8jq6_9pnxkwm75f87sdc2",
    "whitelistDomains": [
      "localhost",
      "localhost:8080"
    ]
  }
}

**Comment by thoundernousx** [comment]
So far, I can register at the web-vault. But I get this error: Missing auth header; I am using your neweset version and the newest version of the web-vault. It is 1.22

**Comment by leonghui** [comment]
@shackra 
Thanks, I referenced your dockerfiles to build my own alpine-based containers.
I got this to work using reverse proxy with the vaultURL parameter.

The command I used is as follows. The Vault container IP is in docker's default 172.17../16 subnet.
`bitwarden-go -init -location /data -vaultURL <vault container IP>:4001`

In the Vault container, I copied settings.Production.json to settings.json and changed to `env` tag in package.json. Access is via port 8000 on the bitwarden-go container.

**Comment by VictorNine** [comment]
@thoundernousx Just tried with the latest version. Could you post your settings.json?

**Comment by Nous1699** [comment]
Thanks, I tried it yesterday. Now everything works like a charm.

**Comment by shackra** [comment]
Weird, suddenly I was unable to access Bitwarden-web from the outside running inside a docker container.

I just will use @leonghui alpine versions of both containers and that is.
