### ISSUE TITLE
API Breaking Changes Coming

### ISSUE THREAD

**Issue by kspearrin** [VictorNine/bitwarden-go#23]
Just thought you should know that there are some breaking changes coming to cipher API models.

1. `Cipher.Login.Uri` on the request and response models is being deprecated in favor of `Cipher.Login.Uris`, an array of `{ "Uri": string, "Match": enum }`
2. The cipher response model is being updated to better match the request model. Namely:
    - `Data` prop is being deprecated.
    - Adding: `Name`, `Notes`, and `Fields` to the root object.
    - Adding: `Login`, `Card`, `Identity`, and `SecureNote` to the root object (their prop values were part of the dynamic `Data` property in the past).

Our API will handle these changes in a backwards compatible way for a few iterations since outdated client apps will still be expecting the old models for some time.

These changes are already in the `Core` API project and refactoring is being done in all client apps over the next few days.

**Comment by VictorNine** [comment]
Thanks, I'll update

**Comment by VictorNine** [comment]
Temporary fix implemented. Will work as long as the data field is kept

**Comment by VictorNine** [comment]
implemented
