### ISSUE TITLE
Items appear missing with bitwarden-web v1.23.0

### ISSUE THREAD

**Issue by leonghui** [VictorNine/bitwarden-go#24]
With the latest vault release (v1.23.0), account login, 2FA, and folders work but existing items are missing. 

Registering a new user on a fresh DB works.

Trying to add a new item triggers an error message on vault:
![image](https://user-images.githubusercontent.com/6092315/37354443-a20498f2-271c-11e8-8c5b-9630f2b33a36.png)

Server stdout reports:
`2018/03/13 16:13:27 user@user.com is trying to add data`

Other bitwarden clients are working fine (e.g. Android app, Firefox extension).

Not sure if this is related to the upcoming API changes?

**Comment by VictorNine** [comment]
It probably is due to the API change. Thanks for the issue I'll look in to it.

**Comment by VictorNine** [comment]
Should be working now

**Comment by leonghui** [comment]
Fixed for bitwarden-web v1.23.0, will retest for the latest release.
