### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by Ezak91** [VictorNine/bitwarden-go#31]
root@pi_fhem:~/go# go get github.com/VictorNine/bitwarden-go
package github.com/VictorNine/bitwarden-go: no buildable Go source files in /root/go/src/github.com/VictorNine/bitwarden-go

**Comment by Mohammed90** [comment]
Try `go get github.com/VictorNine/bitwarden-go/cmd/bitwarden-go`

**Comment by Ezak91** [comment]
@Mohammed90  that works for me. Maybe they should update the README.
I also had to chmod 755 bitwarden-go in the bin directory and call with ./bitwarden 

Thank you
