### ISSUE TITLE
Built, installed, ran `bitwarden-go -init`... Now what?

### ISSUE THREAD

**Issue by MarkOnDuty** [VictorNine/bitwarden-go#38]
I believe I have successfully built and installed bitwarden-go. Running `bitwarden-go -init` doesn't terminate, which wasn't what I expected according to README.md, but that's fine.

Trying to connect to server, via port 8000, right from the server or from another host, gets me a 404 error.

Killing `bitwarden-go -init` with ctrl-c and restarting it without the `-init` gets the same result.

I may just have misinterpreted what the server provides. Am I completely wrong in expecting some sort of web interface to be hosted by `bitwarden-go`? Or should I be pointing another client at it?

**Comment by davehope** [comment]
Bitwarden is split into several components , one of which is a backend used to handle authentication, storage and retrieval. That is what this project provides.

You can use bitwarden-go with various frontends, such as the android/iOS apps or with a bit or setup work - bitwarden-web (sometimes call bitwarden vault).

**Comment by MarkOnDuty** [comment]
Thanks for the background.

I actually installed Rust implementation of Bitwarden when the Go implementation didn't act as I expected. The Rust implementation included everything I expected, but that's as far as I got before being pulled away. I will be back at it in the coming weeks, though. Understanding that bitwarden-web is just another front-end will avoid some confusion.
